<a href="https://colab.research.google.com/github/MihirDesh/MovieRec/blob/main/MovieRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
movies = pd.read_csv('top10K-TMDB-movies.csv')

print(movies)

          id                                          title  \
0        278                       The Shawshank Redemption
1      19404                    Dilwale Dulhania Le Jayenge
2        238                                  The Godfather
3        424                               Schindler's List
4        240                         The Godfather: Part II
...      ...                                            ...
9995   10196                             The Last Airbender
9996  331446                       Sharknado 3: Oh Hell No!
9997   13995                                Captain America
9998    2312  In the Name of the King: A Dungeon Siege Tale
9999  455957                                         Domino

                                                 genre original_language  \
0                                          Drama,Crime                en
1                                 Comedy,Drama,Romance                hi
2                                          Drama,Crime                en
3                                    Drama,History,War                en
4                                          Drama,Crime                en
...                                                ...               ...
9995                          Action,Adventure,Fantasy                en
9996  Action,TV Movie,Science Fiction,Comedy,Adventure                en
9997                        Action,Science Fiction,War                en
9998                    Adventure,Fantasy,Action,Drama                en
9999                             Thriller,Action,Crime                en

                                               overview  popularity  \
0     Framed in the 1940s for the double murder of h...      94.075
1     Raj is a rich, carefree, happy-go-lucky second...      25.408
2     Spanning the years 1945 to 1955, a chronicle o...      90.585
3     The true story of how businessman Oskar Schind...      44.761
4     In the continuing saga of the Corleone crime f...      57.749
...                                                 ...         ...
9995  The story follows the adventures of Aang, a yo...      98.322
9996  The sharks take bite out of the East Coast whe...      12.490
9997  During World War II, a brave, patriotic Americ...      18.333
9998  A man named Farmer sets out to rescue his kidn...      15.159
9999  Seeking justice for his partner’s murder by an...      16.482

     release_date  vote_average  vote_count
0      1994-09-23           8.7       21862
1      1995-10-19           8.7        3731
2      1972-03-14           8.7       16280
3      1993-12-15           8.6       12959
4      1974-12-20           8.6        9811
...           ...           ...         ...
9995   2010-06-30           4.7        3347
9996   2015-07-22           4.7         417
9997   1990-12-14           4.6         332
9998   2007-11-29           4.7         668
9999   2019-05-31           4.6         221

[10000 rows x 9 columns]

In [2]:
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [3]:
movies = movies[['id', 'title', 'overview', 'genre']]
movies

,id,title,overview,genre
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy"
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure"
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War"
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama"
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime"

In [4]:
movies['tags'] = movies['overview'] + movies['genre']
new_data = movies.drop(columns = ['overview', 'genre'])
new_data

<ipython-input-4-311c542b5183>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'] + movies['genre']

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000, stop_words='english')
cv

CountVectorizer(max_features=10000, stop_words='english')

In [6]:
vector = cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [7]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)

In [8]:
new_data[new_data['title'] == "The Godfather"].index[0]

2

In [9]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key = lambda vector:vector[1])
for i in distance[0:5]:
  print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City

In [10]:
def recommend(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [20]:
recommend("Star Wars: Episode III - Revenge of the Sith")

Star Wars: Episode III - Revenge of the Sith
Star Wars: Episode I - The Phantom Menace
Star Wars: Episode II - Attack of the Clones
Mighty Morphin Power Rangers: The Movie
Star Wars: The Rise of Skywalker

In [12]:
import pickle

In [13]:
pickle.dump(new_data, open('movies_list.pkl', 'wb'))

In [14]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [15]:
pickle.load(open('movies_list.pkl', 'rb'))

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...